import { usePaymentStore } from '../stores/paymentStore';

export function usePayment() {
  const { 
    paymentMethods,
    genericPaymentStatus,
    mpesaPaymentStatus,
    pesapalPaymentStatus,
    initiatedPayment,
    verifiedPayment,
    mpesaStkPushResult,
    flutterwavePayResult,
    flutterwaveVerifyResult,
    dpoCreateResult,
    dpoVerifyResult,
    pesapalCreateResult,
    successPayload,
    failedPayload,
    isLoading, 
    error,
    getPaymentMethods,
    getPaymentStatus,
    initiate,
    verify,
    mpesaStkPush,
    mpesaStatus,
    flutterwavePay,
    flutterwaveVerify,
    dpoCreate,
    dpoVerify,
    pesapalCreate,
    pesapalStatus,
    pesapalStatusByPaymentId,
    paymentSuccess,
    paymentFailed
  } = usePaymentStore();

  return {
    paymentMethods,
    paymentStatus: genericPaymentStatus,
    mpesaPaymentStatus,
    pesapalPaymentStatus,
    initiatedPayment,
    verifiedPayment,
    mpesaStkPushResult,
    flutterwavePayResult,
    flutterwaveVerifyResult,
    dpoCreateResult,
    dpoVerifyResult,
    pesapalCreateResult,
    successPayload,
    failedPayload,
    isLoading,
    error,
    getPaymentMethods,
    getPaymentStatus,
    initiatePayment: initiate,
    verifyPayment: verify,
    mpesaStkPush,
    mpesaStatus,
    flutterwavePay,
    flutterwaveVerify,
    dpoCreate,
    dpoVerify,
    pesapalCreate,
    pesapalStatus,
    pesapalStatusByPaymentId,
    paymentSuccess,
    paymentFailed
  };
}
